import { MenuFilterTable } from '../../../../shared/models/reusables/filter-menu-states.interface';
import { GenericButton } from '../../../../shared/models/reusables/generic-button.interface';
import { TableColumns } from '../../../../shared/models/reusables/list-table.interface';
import { SplitButton } from '../../../../shared/models/reusables/split-button.interface';
import { GenericValidators } from '../../../../shared/utils/generic-validators.util';
import {
  SPLIT_BUTTON_ACTIONS,
  STATUS,
} from '../../../../shared/utils/global-constants.util';
import { InventoryResponse } from '../../models/inventory-response.interface';

const tableColumns: TableColumns<InventoryResponse>[] = [
    {
        label: 'IMAGEN',
        cssLabel: ['font-bold', 'text-xs', 'text-am-main-blue-dark'],
        property: 'image',
        cssProperty: [
          'text-xs',
          'uppercase',
          'font-bold',
          'whitespace-normal',
          'max-w-120',
        ],
        type: 'image',
        sticky: false,
        sort: true,
        sortProperty: 'image',
        visible: true,
        download: true,
      },
  {
    label: 'CODIGO',
    cssLabel: ['font-bold', 'text-xs', 'text-am-main-blue-dark'],
    property: 'code',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'code',
    visible: true,
    download: true,
  },
  {
    label: 'ACTIVO',
    cssLabel: ['font-bold', 'text-xs', 'text-am-main-blue-dark'],
    property: 'active',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'active',
    visible: true,
    download: true,
  },
  {
    label: 'TIPO DE EQUIPO',
    cssLabel: ['font-bold', 'text-xs', 'text-am-main-blue-dark'],
    property: 'equipmentTypeName',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'equipmentTypeName',
    visible: true,
    download: true,
  },
  {
    label: 'MARCA',
    cssLabel: ['font-bold', 'text-sm', 'text-am-main-blue-dark'],
    property: 'brand',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'brand',
    visible: true,
    download: true,
  },
  {
    label: 'NUMERO DE SERIE',
    cssLabel: ['font-bold', 'text-sm', 'text-am-main-blue-dark'],
    property: 'series',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'series',
    visible: true,
    download: true,
  },
  {
    label: 'MODELO',
    cssLabel: ['font-bold', 'text-sm', 'text-am-main-blue-dark'],
    property: 'model',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'text',
    sticky: false,
    sort: true,
    sortProperty: 'model',
    visible: true,
    download: true,
  },
  {
    label: 'PRECIO',
    cssLabel: ['font-bold', 'text-sm', 'text-am-main-blue-dark'],
    property: 'price',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'number',
    sticky: false,
    sort: true,
    sortProperty: 'price',
    visible: true,
    download: true,
  },
  {
    label: 'F. DE CREACIÓN',
    cssLabel: ['font-bold', 'text-sm', 'text-am-main-blue-dark'],
    property: 'auditCreateDate',
    cssProperty: [
      'text-xs',
      'uppercase',
      'font-bold',
      'whitespace-normal',
      'max-w-120',
    ],
    type: 'datetime',
    sticky: false,
    sort: true,
    visible: true,
    download: true,
  },
  {
    label: 'ESTADO',
    cssLabel: [
      'font-bold',
      'text-sm',
      'text-am-main-blue-dark',
      'mat-sort-header-text-center',
    ],
    property: 'stateInventory',
    cssProperty: [],
    type: 'simpleBadge',
    sticky: false,
    sort: false,
    visible: true,
    download: true,
  },
  {
    label: '',
    cssLabel: [],
    property: 'download',
    cssProperty: [],
    type: 'icon',
    sticky: false,
    sort: false,
    sortProperty: '',
    visible: true,
    action: 'download',
    icon: 'download',
    cssIcon: 'material-icons color_green',
    tooltip: 'Descargar Codigo QR',
  },
  {
    label: '',
    cssLabel: [],
    property: 'edit',
    cssProperty: [],
    type: 'icon',
    sticky: false,
    sort: false,
    sortProperty: '',
    visible: true,
    action: 'edit',
    icon: 'edit',
    cssIcon: 'material-icons color_blue',
    tooltip: 'Actualizar Inventario',
  },
  {
    label: '',
    cssLabel: [],
    property: 'delete',
    cssProperty: [],
    type: 'icon',
    sticky: false,
    sort: false,
    sortProperty: '',
    visible: true,
    action: 'delete',
    icon: 'delete',
    cssIcon: 'material-icons color_red',
    tooltip: 'Eliminar Inventario',
  },
];

const actionButtonInventory: GenericButton = {
  label: 'Crear inventario',
  icon: 'add_circle',
  tooltip: 'Crear nuevo inventario',
};

const searchOptions = [
  {
    label: 'Codigo',
    value: 1,
    placeholder: 'Buscar por codigo',
    icon: 'badge',
  },
  {
    label: 'Activo',
    value: 2,
    placeholder: 'Buscar por activo',
    icon: 'badge',
  },
  {
    label: 'Tipo de Equipo',
    value: 3,
    placeholder: 'Buscar por tipo de equipo',
    validation: [GenericValidators.defaultDescription],
    validation_desc: 'Permite búsqueda por las primeras tres letras.',
    icon: 'badge',
  },
  {
    label: 'Marca',
    value: 4,
    placeholder: 'Buscar por marca',
    validation: [GenericValidators.emailValidation],
    validation_desc: 'Permite búsqueda por las primeras tres letras.',
    icon: 'badge',
  },
  {
    label: 'Marca',
    value: 5,
    placeholder: 'Buscar por marca',
    icon: 'badge',
  },
  {
    label: 'Modelo',
    value: 5,
    placeholder: 'Buscar por modelo',
    icon: 'badge',
  },
];

const menuItems: MenuFilterTable = {
  label: 'Estados',
  icon: 'filter_list',
  tooltip: 'Estados',
  menuItems: [
    {
      label: 'Activo',
      icon: 'label',
      cssIcon: ['text-am-new-green'],
      value: STATUS.ACTIVO,
    },
    {
      label: 'Inactivo',
      icon: 'label',
      cssIcon: ['text-am-gray-light'],
      value: STATUS.INACTIVO,
    },
  ],
};

const filterButtons: SplitButton[] = [
  {
    type: 'button',
    icon: 'refresh',
    label: 'Actualizar listado',
    value: SPLIT_BUTTON_ACTIONS.ACTUALIZAR_DATOS,
  },
  {
    type: 'action',
    id: 'Pendiente',
    icon: 'restart_alt',
    label: 'Refrescar filtros',
    value: SPLIT_BUTTON_ACTIONS.REFRESCAR_FILTROS,
    classes: {
      icon: 'text-am-main-blue-dark text-md',
    },
  },
];

const initFilters = {
  numFilter: 0,
  textFilter: '',
  stateFilter: STATUS.ACTIVO + '-' + STATUS.INACTIVO,
  startDate: '',
  endDate: '',
  refresh: false,
};

const filters = {
  numFilter: 0,
  textFilter: '',
  stateFilter: STATUS.ACTIVO + '-' + STATUS.INACTIVO,
  startDate: '',
  endDate: '',
  refresh: false,
};

export const componentSetting = {
  tableColumns,
  actionButtonInventory,
  searchOptions,
  menuItems,
  filterButtons,
  initFilters,
  filters,
  initialSort: 'Id',
  initalSortDir: 'desc',
  getInputs: '',
  filename: 'lista-de-inventarios',
};
